### ISSUE TITLE
Sorastream

### ISSUE THREAD

**Issue by hexated** [dexter21767/cinestream#1]
From sorastream hexated?

Add credits & follow GNU license
(same case with loklok)

**Comment by dexter21767** [comment]
added credit.
and loklok is not related to yours.

**Comment by hexated** [comment]
No, i don't say added credit to my repo,

To this.

https://github.com/napthedev/filmhot for providing API

Its from my hoomies

**Comment by dexter21767** [comment]
tbh i don't see how any of you are entitled to credits since i am
using the consumet
API
<https://icsau.com/click?redirect=https%3A%2F%2Fdocs.consumet.org%2F&dID=1667581156692&linkName=consumet
API>. I still gave credit out of respect tho.
